name: Build and push image

on:
  push:
    branches:
      - 'dev-0.17.0'
    tags:
      - '*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push clickhouse-operator
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile/operator/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/altinity-clickhouse-operator:latest
      -
        name: Build and push metrics-exporter
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile/metrics-exporter/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/altinity-metrics-exporter:latest